universityAdmidAPP/Models/ErrorViewModel.cs
namespace universityAdmidAPP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

universityAdmidAPP/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace universityAdmidAPP.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Signin()
        {
            return View();
        }
        public IActionResult forgetpwd()
        {
            return View();
        }
       


    }
}

universityAdmidAPP/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;

namespace universityAdmidAPP.Controllers
{
    public class ApplicationController : Controller
    {
        public IActionResult apps()
        {
            return View();
        }
        public IActionResult process()
        {
            return View();
        }
    }
}

universityAdmidAPP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using universityAdmidAPP.Models;

namespace universityAdmidAPP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

universityAdmidAPP/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace universityAdmidAPP.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult register()
        {
            return View();
        }
    }
}

universityAdmidAPP/Controllers/dashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace universityAdmidAPP.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

universityAdmidAPP/Views/Application/apps.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
     Layout = "_Layout2";
}
<h1 class="text-center" >Applications </h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Abdikarin Mohamed Ali</td>
      <td>abdikarin@gmail.com</td>
      <td>Student</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Abdimalik Sadak Abdirahman</td>
      <td>abdimalik@gmail.com</td>
      <td>student</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Mohamed Abukar</td>
      <td>mohamed@gmail.com</td>
      <td>student</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>Yusuf Abdi Mohamed</td>
      <td>yusuf@mail.com</td>
      <td>student</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>Zakaria Ali Nor</td>
      <td>zakaria@gmail.com</td>
      <td>student</td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td>Ahmed Kalif Mumin</td>
      <td>ahmed@mail.com</td>
      <td>student</td>
    </tr>
    <tr>
      <th scope="row">7</th>
      <td>Abdigafar Jeylani Omar</td>
      <td>abdigafar@gmail.com</td>
      <td>student</td>
    </tr>
  </tbody>
</table>

universityAdmidAPP/Views/Application/process.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

universityAdmidAPP/Views/Dashboard/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
      Layout = "_Layout2";
}
<h1 class="text-center" >Dashboard</h1>

universityAdmidAPP/Views/Home/Index.cshtml
@{

   Layout = "_Layout";
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

universityAdmidAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admision Portal</title>
     <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/universityAdmidAPP.styles.css" asp-append-version="true" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Admision portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          
               <a class="nav-link text-dark active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <span class="visually-hidden">(current)</span>
              
          
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admision</a>
          <div class="dropdown-menu">
           
           
            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Register">APPLY</a>
            
          </div>
        </li>
      </ul>
      <form class="d-flex">
        
        
               <a class="nav-link text-dark active" asp-area="" asp-controller="Account" asp-action="Signin">Signin</a>
            <span class="visually-hidden">(current)</span>
             
             
      </form>
    </div>
  </div>
</nav>










    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Admision portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

universityAdmidAPP/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admision Portal</title>
     <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Layout2.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/universityAdmidAPP.styles.css" asp-append-version="true"/>
     <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
</head>
<body>
    
    <div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a href="#">pro sidebar</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
            alt="User picture">
        </div>
        <div class="user-info">
          <span class="user-name">Abdakarin
            <strong>Mahamed</strong>
          </span>
          <span class="user-role">Administrator</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Search...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li>
             <a asp-controller="dashboard" asp-action="Dashboard">
             
              
            
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard</span>
              
            </a>
            
          </li>
          <li>
           
            
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
           <i class="fa fa-folder"></i>
              <span>Applicatiom Management</span>

            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                   <a class="nav-link text-dark active" asp-area="" asp-controller="Application" asp-action="Apps">applications</a>

                
              </ul>
            </div>
          </li>
          
          <li >
             <a  asp-controller="" asp-action="">
            <i class="fas fa-spinner"></i>
              <span>Process</span>
            </a>
            
          </li>
          
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification">7</span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
      </a>
      <a href="#">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </nav>
  <!-- sidebar-wrapper  -->
  <main class="page-content">
    <div class="container-fluid">
      @RenderBody()
    </div>
  </main>
  <!-- page-content" -->
</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Layout2js.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>